# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
config.vm.box = "sbeliakou/centos"
config.vm.box_version = "7.5"
config.vm.define "jenkins" do |config|
  config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory= 2048
      vb.name='jenkins'
end
  config.vm.network  "private_network", ip: "192.168.1.2"
  config.vm.hostname="jenkins"
  config.vm.synced_folder "/home/student/Documents/ppt/Jenkins/jenkins", "/opt/jenkins"
end
end
